// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIly90AsR1I9xdTAdMXxSx0pfk8H6YjsA',
    appId: '1:545807190708:web:783fbcbddf12e6f27025e1',
    messagingSenderId: '545807190708',
    projectId: 'pole-hole-storage',
    authDomain: 'pole-hole-storage.firebaseapp.com',
    databaseURL: 'https://pole-hole-storage-default-rtdb.firebaseio.com',
    storageBucket: 'pole-hole-storage.firebasestorage.app',
    measurementId: 'G-825V6HWZMW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4ivjwo99dhL2brNpNJVTsz_pN--a2u8w',
    appId: '1:545807190708:android:056db62e8cd0ad657025e1',
    messagingSenderId: '545807190708',
    projectId: 'pole-hole-storage',
    databaseURL: 'https://pole-hole-storage-default-rtdb.firebaseio.com',
    storageBucket: 'pole-hole-storage.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdbzCt0LAx3KdGhwRmsDMzFk4xMZjiWUA',
    appId: '1:545807190708:ios:7402a0a0acaac3ea7025e1',
    messagingSenderId: '545807190708',
    projectId: 'pole-hole-storage',
    databaseURL: 'https://pole-hole-storage-default-rtdb.firebaseio.com',
    storageBucket: 'pole-hole-storage.firebasestorage.app',
    iosBundleId: 'com.example.poleHoleApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdbzCt0LAx3KdGhwRmsDMzFk4xMZjiWUA',
    appId: '1:545807190708:ios:7402a0a0acaac3ea7025e1',
    messagingSenderId: '545807190708',
    projectId: 'pole-hole-storage',
    databaseURL: 'https://pole-hole-storage-default-rtdb.firebaseio.com',
    storageBucket: 'pole-hole-storage.firebasestorage.app',
    iosBundleId: 'com.example.poleHoleApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCIly90AsR1I9xdTAdMXxSx0pfk8H6YjsA',
    appId: '1:545807190708:web:4d74d69be29c66fc7025e1',
    messagingSenderId: '545807190708',
    projectId: 'pole-hole-storage',
    authDomain: 'pole-hole-storage.firebaseapp.com',
    databaseURL: 'https://pole-hole-storage-default-rtdb.firebaseio.com',
    storageBucket: 'pole-hole-storage.firebasestorage.app',
    measurementId: 'G-W8E542Q2BG',
  );
}
